import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next Tutorial | Rayani Gomes",
    template: "%s | Rayani Gomes",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-green-500">Cabeçalho</header>
        <div>{children}</div>
        <footer className="bg-green-500">Rodapé</footer>
      </body>
    </html>
  );
}
